name: CI

on: pull_request

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Installing dependencies
        uses: php-actions/composer@v6 
      - name: Running unit test
        uses: php-actions/phpunit@v3
        with:
          version: 9.6
          php_version: 8.4
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-clover=coverage.xml
        
        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v6
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
